version: '3'

volumes:
  jenkins_home:

services:
  jenkins: 
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      